//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by common.rc
//
#define VER_BUGFIX                      0x0000
#define VER_BUILD                       0x0000
#define VER_MAJOR                       0x0001
#define VER_MINOR                       0x00001
#define IDD_DIALOG1                                   1000
#define IDB_BITMAP1                                   1001
#define IDB_BANNER                                    1002
#define IDI_LOGO                                      1003
#define IDM_MAIN                                      1004
#define IDA_MAIN                                      1005
#define IDS_MAIN                                      1006
#define IDD_ABOUT                                     1007
#define IDD_STATS                                     1008
#define IDD_UNITSEL1                                  1009
#define IDD_UNITSEL2                                  1010
#define IDD_PLAYERS                                   1011
#define IDD_MSGS                                      1012
#define IDD_PLAYER                                    1013
#define IDD_AI                                        1014
#define IDD_CTY                                       1015
#define IDD_VICTORY                                   1016
#define IDD_DISABLES                                  1017
#define IDD_TERRAIN                                   1018
#define IDD_UNITS                                     1019
#define IDD_TRIGGERS                                  1020
#define IDD_TRIGTEXT                                  1021
#define IDD_MAPINSPECT                                1022
#define IDD_EFFECT                                    1023
#define IDD_COND                                      1024
#define IDB_LOGO                                      1025
#define IDB_TRIG_ON_GOOD                              1026
#define IDB_TRIG_ON_BAD                               1027
#define IDB_TRIG_OFF_GOOD                             1028
#define IDB_TRIG_OFF_BAD                              1029
#define IDB_LOOP_ON_GOOD                              1030
#define IDB_LOOP_ON_BAD                               1031
#define IDB_LOOP_OFF_GOOD                             1032
#define IDB_LOOP_OFF_BAD                              1033
#define IDB_COND_GOOD                                 1034
#define IDB_COND_BAD                                  1035
#define IDB_EFFECT_GOOD                               1036
#define IDB_EFFECT_BAD                                1037
#define IDC_M_MSGS                                    1038
#define IDC_M_CINEM                                   1039
#define IDC_M_STABLE                                  1040
#define IDC_M_EXPORT                                  1041
#define IDC_M_SEL                                     1042
#define IDC_M_SELC                                    1043
#define IDC_G_VER                                     1044
#define IDC_S_PLAYERS                                 1045
#define IDC_G_GAME                                    1046
#define IDC_G_TIMESTAMP                               1047
#define IDC_S_TRIGGERS                                1048
#define IDC_G_ONAME                                   1049
#define IDC_S_CONDITIONS                              1050
#define IDC_S_EFFECTS                                 1051
#define IDC_S_MAPSIZE                                 1052
#define IDC_G_ALLTECHS                                1053
#define IDC_G_X                                       1054
#define IDC_S_UNITS                                   1055
#define IDC_G_Y                                       1056
#define IDC_S_UNITS1                                  1057
#define IDC_S_UNITS2                                  1058
#define IDC_S_UNITS3                                  1059
#define IDC_S_UNITS4                                  1060
#define IDC_S_UNITS5                                  1061
#define IDC_S_UNITS6                                  1062
#define IDC_S_UNITS7                                  1063
#define IDC_S_UNITS8                                  1064
#define IDC_S_UNITS9                                  1065
#define IDC_G_NEXTID                                  1066
#define IDC_G_LOCKTEAMS                               1067
#define IDC_M_USERPATCH                               1068
#define IDC_G_CHOOSETEAMS                             1069
#define IDC_G_RANDPOSITIONS                           1070
#define IDC_S_DISABLE                                 1071
#define IDC_S_DISABLE1                                1072
#define IDC_S_DISABLE2                                1073
#define IDC_S_DISABLE3                                1074
#define IDC_S_DISABLE4                                1075
#define IDC_S_DISABLE5                                1076
#define IDC_S_DISABLE6                                1077
#define IDC_S_DISABLE7                                1078
#define IDC_S_DISABLE8                                1079
#define IDC_S_DISABLE9                                1080
#define IDC_P_SP1                                     1081
#define IDC_P_SP2                                     1082
#define IDC_P_SP3                                     1083
#define IDC_P_SP4                                     1084
#define IDC_P_SP5                                     1085
#define IDC_P_SP6                                     1086
#define IDC_P_SP7                                     1087
#define IDC_P_SP8                                     1088
#define IDC_P_SG                                      1089
#define IDC_P_CTY_SP1                                 1090
#define IDC_P_CTY_SP2                                 1091
#define IDC_P_CTY_SP3                                 1092
#define IDC_P_CTY_SP4                                 1093
#define IDC_P_CTY_SP5                                 1094
#define IDC_P_CTY_SP6                                 1095
#define IDC_P_CTY_SP7                                 1096
#define IDC_P_CTY_SP8                                 1097
#define IDC_P_CTY_SG                                  1098
#define IDC_P_VC_SP1                                  1099
#define IDC_P_VC_SP2                                  1100
#define IDC_P_VC_SP3                                  1101
#define IDC_P_VC_SP4                                  1102
#define IDC_P_VC_SP5                                  1103
#define IDC_P_VC_SP6                                  1104
#define IDC_P_VC_SP7                                  1105
#define IDC_P_VC_SP8                                  1106
#define IDC_P_VC_SG                                   1107
#define IDC_P_STABLE                                  1108
#define IDC_P_ACTIVE                                  1109
#define IDC_P_NAME1                                   1110
#define IDC_P_NAME2                                   1111
#define IDC_P_NAME3                                   1112
#define IDC_P_NAME4                                   1113
#define IDC_P_NAME5                                   1114
#define IDC_P_NAME6                                   1115
#define IDC_P_NAME7                                   1116
#define IDC_P_NAME8                                   1117
#define IDC_P_NAME9                                   1118
#define IDC_P_HUMAN1                                  1119
#define IDC_P_HUMAN2                                  1120
#define IDC_P_HUMAN3                                  1121
#define IDC_P_HUMAN4                                  1122
#define IDC_P_HUMAN5                                  1123
#define IDC_P_HUMAN6                                  1124
#define IDC_P_HUMAN7                                  1125
#define IDC_P_HUMAN8                                  1126
#define IDC_P_HUMAN9                                  1127
#define IDC_P_FOOD1                                   1128
#define IDC_P_FOOD2                                   1129
#define IDC_P_FOOD3                                   1130
#define IDC_P_FOOD4                                   1131
#define IDC_P_FOOD5                                   1132
#define IDC_P_FOOD6                                   1133
#define IDC_P_FOOD7                                   1134
#define IDC_P_FOOD8                                   1135
#define IDC_P_FOOD9                                   1136
#define IDC_P_WOOD1                                   1137
#define IDC_P_WOOD2                                   1138
#define IDC_P_WOOD3                                   1139
#define IDC_P_WOOD4                                   1140
#define IDC_P_WOOD5                                   1141
#define IDC_P_WOOD6                                   1142
#define IDC_P_WOOD7                                   1143
#define IDC_P_WOOD8                                   1144
#define IDC_P_WOOD9                                   1145
#define IDC_P_GOLD1                                   1146
#define IDC_P_GOLD2                                   1147
#define IDC_P_GOLD3                                   1148
#define IDC_P_GOLD4                                   1149
#define IDC_P_GOLD5                                   1150
#define IDC_P_GOLD6                                   1151
#define IDC_P_GOLD7                                   1152
#define IDC_P_GOLD8                                   1153
#define IDC_P_GOLD9                                   1154
#define IDC_P_STONE1                                  1155
#define IDC_P_STONE2                                  1156
#define IDC_P_STONE3                                  1157
#define IDC_P_STONE4                                  1158
#define IDC_P_STONE5                                  1159
#define IDC_P_STONE6                                  1160
#define IDC_P_STONE7                                  1161
#define IDC_P_STONE8                                  1162
#define IDC_P_STONE9                                  1163
#define IDC_P_POP1                                    1164
#define IDC_P_POP2                                    1165
#define IDC_P_POP3                                    1166
#define IDC_P_POP4                                    1167
#define IDC_P_POP5                                    1168
#define IDC_P_POP6                                    1169
#define IDC_P_POP7                                    1170
#define IDC_P_POP8                                    1171
#define IDC_P_POP9                                    1172
#define IDC_P_COLOR1                                  1173
#define IDC_P_COLOR2                                  1174
#define IDC_P_COLOR3                                  1175
#define IDC_P_COLOR4                                  1176
#define IDC_P_COLOR5                                  1177
#define IDC_P_COLOR6                                  1178
#define IDC_P_COLOR7                                  1179
#define IDC_P_COLOR8                                  1180
#define IDC_P_COLOR9                                  1181
#define IDC_P_AGE1                                    1182
#define IDC_P_AGE2                                    1183
#define IDC_P_AGE3                                    1184
#define IDC_P_AGE4                                    1185
#define IDC_P_AGE5                                    1186
#define IDC_P_AGE6                                    1187
#define IDC_P_AGE7                                    1188
#define IDC_P_AGE8                                    1189
#define IDC_P_AGE9                                    1190
#define IDC_P_CIV1                                    1191
#define IDC_P_CIV2                                    1192
#define IDC_P_CIV3                                    1193
#define IDC_P_CIV4                                    1194
#define IDC_P_CIV5                                    1195
#define IDC_P_CIV6                                    1196
#define IDC_P_CIV7                                    1197
#define IDC_P_CIV8                                    1198
#define IDC_P_CIV9                                    1199
#define IDC_P_P1_NUM                                  1200
#define IDC_P_P2_NUM                                  1201
#define IDC_P_P3_NUM                                  1202
#define IDC_P_P4_NUM                                  1203
#define IDC_P_P5_NUM                                  1204
#define IDC_P_P6_NUM                                  1205
#define IDC_P_P7_NUM                                  1206
#define IDC_P_P8_NUM                                  1207
#define IDC_P_P9_NUM                                  1208
#define IDC_P_SWAPP1                                  1209
#define IDC_P_SWAPP2                                  1210
#define IDC_P_SWAPP3                                  1211
#define IDC_P_SWAPP4                                  1212
#define IDC_P_SWAPP5                                  1213
#define IDC_P_SWAPP6                                  1214
#define IDC_P_SWAPP7                                  1215
#define IDC_P_SWAPP8                                  1216
#define IDC_P_SWAPGA                                  1217
#define IDC_P_TEAM1                                   1218
#define IDC_P_TEAM2                                   1219
#define IDC_P_TEAM3                                   1220
#define IDC_P_TEAM4                                   1221
#define IDC_P_TEAM5                                   1222
#define IDC_P_TEAM6                                   1223
#define IDC_P_TEAM7                                   1224
#define IDC_P_TEAM8                                   1225
#define IDC_P_TEAM9                                   1226
#define IDC_P_AI                                      1227
#define IDC_P_X                                       1228
#define IDC_P_Y                                       1229
#define IDC_P_EXAI                                    1230
#define IDC_P_OREX                                    1231
#define IDC_P_SPDIP                                   1232
#define IDC_P_DSTATE                                  1233
#define IDC_P_AV                                      1234
#define IDC_P_IMAI                                    1235
#define IDC_P_AIMODE                                  1236
#define IDC_P_DSTATE1                                 1237
#define IDC_P_DSTATE2                                 1238
#define IDC_P_DSTATE3                                 1239
#define IDC_P_DSTATE4                                 1240
#define IDC_P_DSTATE5                                 1241
#define IDC_P_DSTATE6                                 1242
#define IDC_P_DSTATE7                                 1243
#define IDC_P_DSTATE8                                 1244
#define IDC_P_DSTATE9                                 1245
#define IDC_P_UF                                      1246
#define IDC_P_US0                                     1247
#define IDC_P_US1                                     1248
#define IDC_P_LBL_FOOD                                1249
#define IDC_P_LBL_WOOD                                1250
#define IDC_P_LBL_GOLD                                1251
#define IDC_P_LBL_STONE                               1252
#define IDC_P_LBL_OREX                                1253
#define IDC_P_AISCRIPT                                1254
#define IDC_P_CLEARAI                                 1255
#define IDC_P_RANDOMGAME                              1256
#define IDC_P_PROMISORY                               1257
#define IDC_P_AIMODE_VAL                              1258
#define IDC_P_CLEARVC                                 1259
#define IDC_P_IMVC                                    1260
#define IDC_P_EXVC                                    1261
#define IDC_P_CLEARCTY                                1262
#define IDC_P_IMCTY                                   1263
#define IDC_P_EXCTY                                   1264
#define IDC_P_VCSCRIPT                                1265
#define IDC_P_CTYSCRIPT                               1266
#define IDC_P_CTY                                     1267
#define IDC_P_VC                                      1268
#define IDC_P_OREY                                    1269
#define IDC_P_LBL_OREY                                1270
#define IDC_P_NUM_PLAYERS                             1271
#define IDC_P_MAX_TEAMS                               1272
#define IDC_T_TREE                                    1273
#define IDC_P_TOAOFE                                  1274
#define IDC_TT_VIEW                                   1275
#define IDC_T_NAME                                    1276
#define IDC_P_TO1C                                    1277
#define IDC_TT_EXPORT                                 1278
#define IDC_T_STATE                                   1279
#define IDC_P_TOUP                                    1280
#define IDC_TT_SEARCHTEXT                             1281
#define IDC_T_LOOP                                    1282
#define IDC_P_TOHD                                    1283
#define IDC_TT_FINDNEXT                               1284
#define IDC_T_OBJ                                     1285
#define IDC_TT_CONTEXT                                1286
#define IDC_T_ORDER                                   1287
#define IDC_T_DESC                                    1288
#define IDC_T_EDIT                                    1289
#define IDC_T_NCOND                                   1290
#define IDC_T_NEFFECT                                 1291
#define IDC_T_DEL                                     1292
#define IDC_T_ADD                                     1293
#define IDC_T_DUPP                                    1294
#define IDC_T_DESCID                                  1295
#define IDC_T_OBJSTATE                                1296
#define IDC_T_UNKNOWN                                 1297
#define IDC_T_GOTO                                    1298
#define IDC_T_SHOWFIREORDER                           1299
#define IDC_T_SHOWDISPLAYORDER                        1300
#define IDC_T_SYNC                                    1301
#define IDC_T_START                                   1302
#define IDC_T_END                                     1303
#define IDC_T_DEST                                    1304
#define IDC_T_MOVE                                    1305
#define IDC_T_DELETE                                  1306
#define IDC_T_DUPRANGE                                1307
#define IDC_T_DESELECT                                1308
#define IDC_T_ADD_ACTIVATION                          1309
#define IDC_T_PSEUDONYMS                              1310
#define IDC_T_GOLIST                                  1311
#define IDC_T_SOURCE                                  1312
#define IDC_T_TARGET                                  1313
#define IDC_V_SSTD                                    1314
#define IDC_V_SCONQ                                   1315
#define IDC_V_SSCORE                                  1316
#define IDC_V_STIME                                   1317
#define IDC_V_SCUSTOM                                 1318
#define IDC_V_ALL                                     1319
#define IDC_V_SCORE                                   1320
#define IDC_V_TIME                                    1321
#define IDC_V_RELICS                                  1322
#define IDC_V_EXPL                                    1323
#define IDC_V_CONQUEST                                1324
#define IDC_TR_AITYPE                                 1325
#define IDC_TR_SIZE                                   1326
#define IDC_TR_TX                                     1327
#define IDC_TR_TY                                     1328
#define IDC_TR_ID                                     1329
#define IDC_TR_ELEV                                   1330
#define IDC_TR_MCPASTE                                1331
#define IDC_TR_MCCOPY                                 1332
#define IDC_TR_SIZE2                                  1333
#define IDC_TR_MMX1                                   1334
#define IDC_TR_MMY1                                   1335
#define IDC_TR_MMSET1                                 1336
#define IDC_TR_MMX2                                   1337
#define IDC_P_LBL_FOOD2                               1338
#define IDC_TR_MMY2                                   1339
#define IDC_TR_MMSET2                                 1340
#define IDC_TR_MMXT                                   1341
#define IDC_TR_MMYT                                   1342
#define IDC_TR_MMSETT                                 1343
#define IDC_TR_MMMOVE                                 1344
#define IDC_TR_MDUPT                                  1345
#define IDC_TR_MDUPU                                  1346
#define IDC_TR_NORMALIZE_ELEV                         1347
#define IDC_TR_SAVETILE                               1348
#define IDC_TR_MDUPE                                  1349
#define IDC_TR_FACTOR                                 1350
#define IDC_TR_SCALE                                  1351
#define IDC_TABS                                      1352
#define IDC_TR_SCALE2                                 1353
#define IDC_TR_MOVE_TERRAIN                           1354
#define IDC_TR_MOVE_UNITS                             1355
#define IDC_TR_MOVE_ELEVATION                         1356
#define IDC_TR_MOVE_TRIGGERS                          1357
#define IDC_TR_MMSWAP                                 1358
#define IDC_TR_SWAP_TERRAIN                           1359
#define IDC_TR_SWAP_UNITS                             1360
#define IDC_TR_SWAP_ELEVATION                         1361
#define IDC_TR_SWAP_TRIGGERS                          1362
#define IDC_TR_MDUPTR                                 1363
#define IDC_TR_RMUNITS                                1364
#define IDC_TR_RMTRIGS                                1365
#define IDC_TR_REPEAT                                 1366
#define IDC_TR_REPEAT_UNITS                           1367
#define IDC_TR_REPEAT_TERRAIN                         1368
#define IDC_TR_REPEAT_ELEV                            1369
#define IDC_TR_CONST                                  1370
#define IDC_TR_FLOOD                                  1371
#define IDC_TR_OUTLINE                                1372
#define IDC_TR_OUTLINE_FORCE                          1373
#define IDC_TR_SWAP_TERRAIN_TYPES                     1374
#define IDC_TR_OUTLINE_FORCE_EIGHT                    1375
#define IDC_TR_OUTLINE_EIGHT                          1376
#define IDC_TR_RAISE_ELEV                             1377
#define IDC_TR_LOWER_ELEV                             1378
#define IDC_TR_FLOOD_ELEV                             1379
#define IDC_TR_UNK1                                   1380
#define IDC_TR_UNK2                                   1381
#define IDC_TR_UNK3                                   1382
#define IDC_TR_UNK4                                   1383
#define IDC_TR_CLEAR                                  1384
#define IDC_U_SELU                                    1385
#define IDC_U_SELP                                    1386
#define IDC_U_TYPE                                    1387
#define IDC_U_UNIT                                    1388
#define IDC_U_CONST                                   1389
#define IDC_U_X                                       1390
#define IDC_U_Y                                       1391
#define IDC_U_ROTATE                                  1392
#define IDC_U_FRAME                                   1393
#define IDC_U_ADD                                     1394
#define IDC_U_DEL                                     1395
#define IDC_U_GARRISON                                1396
#define IDC_U_SORT                                    1397
#define IDC_U_ID                                      1398
#define IDC_U_STATE                                   1399
#define IDC_U_Z                                       1400
#define IDC_U_NEXT_AVAIL                              1401
#define IDC_STATIC_NEXT_AVAIL                         1402
#define IDC_U_COMPRESS                                1403
#define IDC_U_RENUMBER                                1404
#define IDC_U_MAKEP1                                  1405
#define IDC_U_MAKEP2                                  1406
#define IDC_U_MAKEP3                                  1407
#define IDC_U_MAKEP4                                  1408
#define IDC_U_MAKEP5                                  1409
#define IDC_U_MAKEP6                                  1410
#define IDC_U_MAKEP7                                  1411
#define IDC_U_MAKEP8                                  1412
#define IDC_U_MAKEGA                                  1413
#define IDC_U_RANDOMIZE_ROT                           1414
#define IDC_U_DEL_TYPE                                1415
#define IDC_U_ROTATE_VAL                              1416
#define IDC_U_DESELECT                                1417
#define IDC_U_RESORT                                  1418
#define IDC_D_SPLY                                    1419
#define IDC_D_STYPE                                   1420
#define IDC_D_ALL                                     1421
#define IDC_D_SEL                                     1422
#define IDC_D_CLR                                     1423
#define IDC_D_DEL                                     1424
#define IDC_D_ADD                                     1425
#define IDC_D_FILL                                    1426
#define IDC_US_UNITS                                  1427
#define IDC_US_SORT                                   1428
#define IDC_US_PLAYER                                 1429
#define IDC_US_NOTE                                   1430
#define IDC_E_TYPE                                    1431
#define IDC_E_AIGOAL                                  1432
#define IDC_E_AMOUNT                                  1433
#define IDC_E_RESTYPE                                 1434
#define IDC_E_DSTATE                                  1435
#define IDC_E_UIDS                                    1436
#define IDC_E_LOCUID                                  1437
#define IDC_E_UCNST                                   1438
#define IDC_E_SPLAY                                   1439
#define IDC_E_TPLAY                                   1440
#define IDC_E_RESEARCH                                1441
#define IDC_E_TEXT                                    1442
#define IDC_E_SOUND                                   1443
#define IDC_E_DTIME                                   1444
#define IDC_E_TRIG                                    1445
#define IDC_E_LOCX                                    1446
#define IDC_E_LOCY                                    1447
#define IDC_E_AREAX1                                  1448
#define IDC_E_AREAY1                                  1449
#define IDC_E_AREAX2                                  1450
#define IDC_E_AREAY2                                  1451
#define IDC_E_AREA_ALL                                1452
#define IDC_E_GROUP                                   1453
#define IDC_E_UTYPE                                   1454
#define IDC_E_PANEL                                   1455
#define IDC_E_STANCE                                  1456
#define IDC_E_SWAPST                                  1457
#define IDC_E_END                                     1458
#define IDC_E_TEXTID                                  1459
#define IDC_E_SOUNDID                                 1460
#define IDC_E_OPENSEL                                 1461
#define IDC_E_OPENSEL2                                1462
#define IDC_E_TRIGID                                  1463
#define IDC_E_UCNSTID                                 1464
#define IDC_E_CLEAR                                   1465
#define IDC_E_TYPEVAL                                 1466
#define IDC_E_VTYPE                                   1467
#define IDC_E_NSELECTED                               1468
#define IDC_E_SIGGOAL                                 1469
#define IDC_E_MAXHEALTH                               1470
#define IDC_C_TYPE                                    1471
#define IDC_C_AMOUNT                                  1472
#define IDC_C_RESTYPE                                 1473
#define IDC_C_UIDOBJ                                  1474
#define IDC_C_UIDLOC                                  1475
#define IDC_C_UCNST                                   1476
#define IDC_C_PLAYER                                  1477
#define IDC_C_RESEARCH                                1478
#define IDC_C_TIMER                                   1479
#define IDC_C_RESERVED                                1480
#define IDC_C_AREA_ALL                                1481
#define IDC_C_AREAX1                                  1482
#define IDC_C_AREAY1                                  1483
#define IDC_C_AREAX2                                  1484
#define IDC_C_AREAY2                                  1485
#define IDC_C_GROUP                                   1486
#define IDC_C_UTYPE                                   1487
#define IDC_C_AISIG                                   1488
#define IDC_C_REVERSEHD                               1489
#define IDC_C_UNKNOWNHD                               1490
#define IDC_C_USEL1                                   1491
#define IDC_C_USEL2                                   1492
#define IDC_C_CLEAR                                   1493
#define IDC_C_REVERSE                                 1494
#define IDC_C_TYPEVAL                                 1495
#define IDC_C_VTYPE                                   1496
#define IDC_C_TAUNT_PLAYER                            1497
#define IDC_C_TAUNT_SET                               1498
#define IDC_C_AIGOAL                                  1499
#define ID_TS_FILE_NEW                                1500
#define ID_TS_FILE_OPEN                               1501
#define ID_TS_FILE_CLOSE                              1502
#define ID_TS_FILE_SAVE                               1503
#define ID_TS_FILE_SAVE_AS                            1504
#define ID_TS_FILE_SAVE_AS2                           1505
#define ID_FILE_DUMP                                  1506
#define ID_FILE_TRIGWRITE                             1507
#define ID_FILE_TRIGREAD                              1508
#define ID_FILE_REOPEN                                1509
#define ID_FILE_RECENT1                               1510
#define ID_FILE_RECENT2                               1511
#define ID_FILE_RECENT3                               1512
#define ID_FILE_RECENT4                               1513
#define ID_EDIT_RENAME                                1514
#define ID_TS_EDIT_COPY                               1515
#define ID_TS_EDIT_CUT                                1516
#define ID_TS_EDIT_PASTE                              1517
#define ID_EDIT_DELETE                                1518
#define ID_EDIT_ALL                                   1519
#define ID_VIEW_STAT_BAR                              1520
#define ID_VIEW_STATISTICS                            1521
#define ID_VIEW_MAP                                   1522
#define ID_TS_APP_ABOUT                               1523
#define ID_TS_APP_EXIT                                1524
#define ID_TS_HELP                                    1525
#define ID_TOOLS_COMPRESS                             1526
#define ID_TOOLS_DECOMPRESS                           1527
#define ID_TRIGGERS_SORT_CONDS_EFFECTS                1528
#define ID_TRIGGERS_HIDENAMES                         1529
#define ID_TRIGGERS_HIDE_DESCRIPTIONS                 1530
#define ID_TRIGGERS_SWAP_NAMES_DESCRIPTIONS           1531
#define ID_TRIGGERS_EXPAND_ALL                        1532
#define ID_TRIGGERS_COMPATIBILITY                     1533
#define ID_TRIGGERS_SAVE_PSEUDONYMS                   1534
#define ID_UNITS_DELETE_ALL                           1535
#define ID_MAP_WATER_CLIFF_INVISIBLE                  1536
#define ID_MAP_WATER_CLIFF_VISIBLE                    1537
#define ID_TRIGGERS_FIXTRIGGEROUTLIERS                1538
#define ID_TRIGGERS_NOPANEL                           1539
#define ID_TRIGGERS_ZERODI                            1540
#define ID_TRIGGERS_RESETDI                           1541
#define ID_TRIGGERS_ZEROPANEL                         1542
#define ID_TRIGGERS_HINTSPANEL                        1543
#define ID_TRIGGERS_ZEROINSTRUCTIONSSOUNDID           1544
#define ID_TRIGGERS_NOINSTRUCTIONSSOUNDID             1545
#define ID_TRIGGERS_NOINSTRUCTIONSSOUND               1546
#define ID_DRAW_TERRAIN                               1547
#define ID_DRAW_ELEVATION                             1548
#define ID_UNITS_TERRAIN_ELEV                         1549
#define IDC_P_AI_SP1                                  1550
#define IDC_P_AI_SP2                                  1551
#define IDC_P_AI_SP3                                  1552
#define IDC_P_AI_SP4                                  1553
#define IDC_P_AI_SP5                                  1554
#define IDC_P_AI_SP6                                  1555
#define IDC_P_AI_SP7                                  1556
#define IDC_P_AI_SP8                                  1557
#define IDC_P_AI_SG                                   1558
#define IDC_PS_SP1                                    1559
#define IDC_PS_SP2                                    1560
#define IDC_PS_SP3                                    1561
#define IDC_PS_SP4                                    1562
#define IDC_PS_SP5                                    1563
#define IDC_PS_SP6                                    1564
#define IDC_PS_SP7                                    1565
#define IDC_PS_SP8                                    1566
#define IDC_PS_SG                                     1567

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
