//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by common.rc
//
#define VER_BUGFIX                      0x0000
#define VER_BUILD                       0x0000
#define VER_MAJOR                       0x0001
#define VER_MINOR                       0x00001
#define IDI_LOGO                        1000
#define IDM_MAIN                        1001
#define IDA_MAIN                        1002
#define IDS_MAIN                        1003
#define IDD_ABOUT                       1004
#define IDD_STATS                       1005
#define IDD_UNITSEL1                    1006
#define IDD_UNITSEL2                    1007
#define IDD_MSGS                        1008
#define IDD_PLAYERSAI                   1009
#define IDD_PLAYERSCTY                  1010
#define IDD_VICTORY                     1011
#define IDD_DISABLES                    1012
#define IDD_TERRAIN                     1013
#define IDD_UNITS                       1014
#define IDD_TRIGGERS                    1015
#define IDD_TRIGTEXT                    1016
#define IDD_MAPINSPECT                  1017
#define IDD_EFFECT                      1018
#define IDD_COND                        1019
#define IDB_LOGO                        1020
#define IDB_TRIG_ON_GOOD                1021
#define IDB_TRIG_ON_BAD                 1022
#define IDB_TRIG_OFF_GOOD               1023
#define IDB_TRIG_OFF_BAD                1024
#define IDB_LOOP_ON_GOOD                1025
#define IDB_LOOP_ON_BAD                 1026
#define IDB_LOOP_OFF_GOOD               1027
#define IDB_LOOP_OFF_BAD                1028
#define IDB_COND_GOOD                   1029
#define IDB_COND_BAD                    1030
#define IDB_EFFECT_GOOD                 1031
#define IDB_EFFECT_BAD                  1032
#define IDC_M_MSGS                      1033
#define IDC_M_CINEM                     1034
#define IDC_M_STABLE                    1035
#define IDC_M_EXPORT                    1036
#define IDC_M_SEL                       1037
#define IDC_M_SELC                      1038
#define IDC_G_VER                       1039
#define IDC_S_PLAYERS                   1040
#define IDC_G_GAME                      1041
#define IDC_G_TIMESTAMP                 1042
#define IDC_S_TRIGGERS                  1043
#define IDC_G_ONAME                     1044
#define IDC_S_CONDITIONS                1045
#define IDC_S_EFFECTS                   1046
#define IDC_S_MAPSIZE                   1047
#define IDC_G_ALLTECHS                  1048
#define IDC_G_X                         1049
#define IDC_S_UNITS                     1050
#define IDC_G_Y                         1051
#define IDC_S_UNITS1                    1052
#define IDC_S_UNITS2                    1053
#define IDC_S_UNITS3                    1054
#define IDC_S_UNITS4                    1055
#define IDC_S_UNITS5                    1056
#define IDC_S_UNITS6                    1057
#define IDC_S_UNITS7                    1058
#define IDC_S_UNITS8                    1059
#define IDC_S_UNITS9                    1060
#define IDC_G_NEXTID                    1061
#define IDC_G_LOCKTEAMS                 1062
#define IDC_M_USERPATCH                 1063
#define IDC_G_CHOOSETEAMS               1064
#define IDC_G_RANDPOSITIONS             1065
#define IDC_S_DISABLE                   1066
#define IDC_S_DISABLE1                  1067
#define IDC_S_DISABLE2                  1068
#define IDC_S_DISABLE3                  1069
#define IDC_S_DISABLE4                  1070
#define IDC_S_DISABLE5                  1071
#define IDC_S_DISABLE6                  1072
#define IDC_S_DISABLE7                  1073
#define IDC_S_DISABLE8                  1074
#define IDC_S_DISABLE9                  1075
#define IDC_P_SP1                       1076
#define IDC_P_SP2                       1077
#define IDC_P_SP3                       1078
#define IDC_P_SP4                       1079
#define IDC_P_SP5                       1080
#define IDC_P_SP6                       1081
#define IDC_P_SP7                       1082
#define IDC_P_SP8                       1083
#define IDC_P_SG                        1084
#define IDC_P_CTY_SP1                   1085
#define IDC_P_CTY_SP2                   1086
#define IDC_P_CTY_SP3                   1087
#define IDC_P_CTY_SP4                   1088
#define IDC_P_CTY_SP5                   1089
#define IDC_P_CTY_SP6                   1090
#define IDC_P_CTY_SP7                   1091
#define IDC_P_CTY_SP8                   1092
#define IDC_P_CTY_SG                    1093
#define IDC_P_VC_SP1                    1094
#define IDC_P_VC_SP2                    1095
#define IDC_P_VC_SP3                    1096
#define IDC_P_VC_SP4                    1097
#define IDC_P_VC_SP5                    1098
#define IDC_P_VC_SP6                    1099
#define IDC_P_VC_SP7                    1100
#define IDC_P_VC_SP8                    1101
#define IDC_P_VC_SG                     1102
#define IDC_P_NAME                      1103
#define IDC_P_STABLE                    1104
#define IDC_P_ACTIVE                    1105
#define IDC_P_HUMAN                     1106
#define IDC_P_AI                        1107
#define IDC_P_CIV                       1108
#define IDC_P_POP                       1109
#define IDC_P_X                         1110
#define IDC_P_Y                         1111
#define IDC_P_COLOR                     1112
#define IDC_P_EXAI                      1113
#define IDC_P_FOOD                      1114
#define IDC_P_WOOD                      1115
#define IDC_P_GOLD                      1116
#define IDC_P_STONE                     1117
#define IDC_P_OREX                      1118
#define IDC_P_SPDIP                     1119
#define IDC_P_DSTATE                    1120
#define IDC_P_AV                        1121
#define IDC_P_IMAI                      1122
#define IDC_P_AGE                       1123
#define IDC_P_AIMODE                    1124
#define IDC_P_UF                        1125
#define IDC_P_US0                       1126
#define IDC_P_US1                       1127
#define IDC_P_LBL_FOOD                  1128
#define IDC_P_LBL_WOOD                  1129
#define IDC_P_LBL_GOLD                  1130
#define IDC_P_LBL_STONE                 1131
#define IDC_P_LBL_OREX                  1132
#define IDC_P_AISCRIPT                  1133
#define IDC_P_CLEARAI                   1134
#define IDC_P_RANDOMGAME                1135
#define IDC_P_PROMISORY                 1136
#define IDC_P_AIMODE_VAL                1137
#define IDC_P_SWAPP1                    1138
#define IDC_P_SWAPP2                    1139
#define IDC_P_SWAPP3                    1140
#define IDC_P_SWAPP4                    1141
#define IDC_P_SWAPP5                    1142
#define IDC_P_SWAPP6                    1143
#define IDC_P_SWAPP7                    1144
#define IDC_P_SWAPP8                    1145
#define IDC_P_SWAPGA                    1146
#define IDC_P_CLEARVC                   1147
#define IDC_P_IMVC                      1148
#define IDC_P_EXVC                      1149
#define IDC_P_CLEARCTY                  1150
#define IDC_P_IMCTY                     1151
#define IDC_P_EXCTY                     1152
#define IDC_P_VCSCRIPT                  1153
#define IDC_P_CTYSCRIPT                 1154
#define IDC_P_CTY                       1155
#define IDC_P_VC                        1156
#define IDC_P_OREY                      1157
#define IDC_P_LBL_OREY                  1158
#define IDC_P_NUM_PLAYERS               1159
#define IDC_P_MAX_TEAMS                 1160
#define IDC_T_TREE                      1161
#define IDC_P_P1_NUM                    1161
#define IDC_P_TOAOFE                    1162
#define IDC_P_P2_NUM                    1162
#define IDC_TT_VIEW                     1163
#define IDC_P_P3_NUM                    1163
#define IDC_T_NAME                      1164
#define IDC_P_P4_NUM                    1164
#define IDC_P_TO1C                      1165
#define IDC_P_P5_NUM                    1165
#define IDC_TT_EXPORT                   1166
#define IDC_P_P6_NUM                    1166
#define IDC_T_STATE                     1167
#define IDC_P_P7_NUM                    1167
#define IDC_P_TOUP                      1168
#define IDC_P_P8_NUM                    1168
#define IDC_TT_SEARCHTEXT               1169
#define IDC_P_P1_NUM9                   1169
#define IDC_P_P9_NUM                    1169
#define IDC_T_LOOP                      1170
#define IDC_P_TOHD                      1171
#define IDC_TT_FINDNEXT                 1172
#define IDC_T_OBJ                       1173
#define IDC_TT_CONTEXT                  1174
#define IDC_T_ORDER                     1175
#define IDC_T_DESC                      1176
#define IDC_T_EDIT                      1177
#define IDC_T_NCOND                     1178
#define IDC_T_NEFFECT                   1179
#define IDC_T_DEL                       1180
#define IDC_T_ADD                       1181
#define IDC_T_DUPP                      1182
#define IDC_T_DESCID                    1183
#define IDC_T_OBJSTATE                  1184
#define IDC_T_UNKNOWN                   1185
#define IDC_T_GOTO                      1186
#define IDC_T_SHOWFIREORDER             1187
#define IDC_T_SHOWDISPLAYORDER          1188
#define IDC_T_SYNC                      1189
#define IDC_T_START                     1190
#define IDC_T_END                       1191
#define IDC_T_DEST                      1192
#define IDC_T_MOVE                      1193
#define IDC_T_DELETE                    1194
#define IDC_T_DUPRANGE                  1195
#define IDC_T_DESELECT                  1196
#define IDC_T_ADD_ACTIVATION            1197
#define IDC_T_PSEUDONYMS                1198
#define IDC_T_GOLIST                    1199
#define IDC_T_SOURCE                    1200
#define IDC_T_TARGET                    1201
#define IDC_V_SSTD                      1202
#define IDC_V_SCONQ                     1203
#define IDC_V_SSCORE                    1204
#define IDC_V_STIME                     1205
#define IDC_V_SCUSTOM                   1206
#define IDC_V_ALL                       1207
#define IDC_V_SCORE                     1208
#define IDC_V_TIME                      1209
#define IDC_V_RELICS                    1210
#define IDC_V_EXPL                      1211
#define IDC_V_CONQUEST                  1212
#define IDC_TR_AITYPE                   1213
#define IDC_TR_SIZE                     1214
#define IDC_TR_TX                       1215
#define IDC_TR_TY                       1216
#define IDC_TR_ID                       1217
#define IDC_TR_ELEV                     1218
#define IDC_TR_MCPASTE                  1219
#define IDC_TR_MCCOPY                   1220
#define IDC_TR_SIZE2                    1221
#define IDC_TR_MMX1                     1222
#define IDC_TR_MMY1                     1223
#define IDC_TR_MMSET1                   1224
#define IDC_TR_MMX2                     1225
#define IDC_TR_MMY2                     1226
#define IDC_TR_MMSET2                   1227
#define IDC_TR_MMXT                     1228
#define IDC_TR_MMYT                     1229
#define IDC_TR_MMSETT                   1230
#define IDC_TR_MMMOVE                   1231
#define IDC_TR_MDUPT                    1232
#define IDC_TR_MDUPU                    1233
#define IDC_TR_NORMALIZE_ELEV           1234
#define IDC_TR_SAVETILE                 1235
#define IDC_TR_MDUPE                    1236
#define IDC_TR_FACTOR                   1237
#define IDC_TR_SCALE                    1238
#define IDC_TABS                        1239
#define IDC_TR_MOVE_TERRAIN             1240
#define IDC_TR_MOVE_UNITS               1241
#define IDC_TR_MOVE_ELEVATION           1242
#define IDC_TR_MOVE_TRIGGERS            1243
#define IDC_TR_MMSWAP                   1244
#define IDC_TR_SWAP_TERRAIN             1245
#define IDC_TR_SWAP_UNITS               1246
#define IDC_TR_SWAP_ELEVATION           1247
#define IDC_TR_SWAP_TRIGGERS            1248
#define IDC_TR_MDUPTR                   1249
#define IDC_TR_RMUNITS                  1250
#define IDC_TR_RMTRIGS                  1251
#define IDC_TR_REPEAT                   1252
#define IDC_TR_REPEAT_UNITS             1253
#define IDC_TR_REPEAT_TERRAIN           1254
#define IDC_TR_REPEAT_ELEV              1255
#define IDC_TR_CONST                    1256
#define IDC_TR_FLOOD                    1257
#define IDC_TR_OUTLINE                  1258
#define IDC_TR_OUTLINE_FORCE            1259
#define IDC_TR_SWAP_TERRAIN_TYPES       1260
#define IDC_TR_OUTLINE_FORCE_EIGHT      1261
#define IDC_TR_OUTLINE_EIGHT            1262
#define IDC_TR_RAISE_ELEV               1263
#define IDC_TR_LOWER_ELEV               1264
#define IDC_TR_FLOOD_ELEV               1265
#define IDC_TR_UNK1                     1266
#define IDC_TR_UNK2                     1267
#define IDC_TR_UNK3                     1268
#define IDC_TR_UNK4                     1269
#define IDC_TR_CLEAR                    1270
#define IDC_U_SELU                      1271
#define IDC_U_SELP                      1272
#define IDC_U_TYPE                      1273
#define IDC_U_UNIT                      1274
#define IDC_U_CONST                     1275
#define IDC_U_X                         1276
#define IDC_U_Y                         1277
#define IDC_U_ROTATE                    1278
#define IDC_U_FRAME                     1279
#define IDC_U_ADD                       1280
#define IDC_U_DEL                       1281
#define IDC_U_GARRISON                  1282
#define IDC_U_SORT                      1283
#define IDC_U_ID                        1284
#define IDC_U_STATE                     1285
#define IDC_U_Z                         1286
#define IDC_U_NEXT_AVAIL                1287
#define IDC_STATIC_NEXT_AVAIL           1288
#define IDC_U_COMPRESS                  1289
#define IDC_U_RENUMBER                  1290
#define IDC_U_MAKEP1                    1291
#define IDC_U_MAKEP2                    1292
#define IDC_U_MAKEP3                    1293
#define IDC_U_MAKEP4                    1294
#define IDC_U_MAKEP5                    1295
#define IDC_U_MAKEP6                    1296
#define IDC_U_MAKEP7                    1297
#define IDC_U_MAKEP8                    1298
#define IDC_U_MAKEGA                    1299
#define IDC_U_RANDOMIZE_ROT             1300
#define IDC_U_DEL_TYPE                  1301
#define IDC_U_ROTATE_VAL                1302
#define IDC_U_DESELECT                  1303
#define IDC_U_RESORT                    1304
#define IDC_D_SPLY                      1305
#define IDC_D_STYPE                     1306
#define IDC_D_ALL                       1307
#define IDC_D_SEL                       1308
#define IDC_D_CLR                       1309
#define IDC_D_DEL                       1310
#define IDC_D_ADD                       1311
#define IDC_D_FILL                      1312
#define IDC_US_UNITS                    1313
#define IDC_US_SORT                     1314
#define IDC_US_PLAYER                   1315
#define IDC_US_NOTE                     1316
#define IDC_E_TYPE                      1317
#define IDC_E_AIGOAL                    1318
#define IDC_E_AMOUNT                    1319
#define IDC_E_RESTYPE                   1320
#define IDC_E_DSTATE                    1321
#define IDC_E_UIDS                      1322
#define IDC_E_LOCUID                    1323
#define IDC_E_UCNST                     1324
#define IDC_E_SPLAY                     1325
#define IDC_E_TPLAY                     1326
#define IDC_E_RESEARCH                  1327
#define IDC_E_TEXT                      1328
#define IDC_E_SOUND                     1329
#define IDC_E_DTIME                     1330
#define IDC_E_TRIG                      1331
#define IDC_E_LOCX                      1332
#define IDC_E_LOCY                      1333
#define IDC_E_AREAX1                    1334
#define IDC_E_AREAY1                    1335
#define IDC_E_AREAX2                    1336
#define IDC_E_AREAY2                    1337
#define IDC_E_AREA_ALL                  1338
#define IDC_E_GROUP                     1339
#define IDC_E_UTYPE                     1340
#define IDC_E_PANEL                     1341
#define IDC_E_STANCE                    1342
#define IDC_E_SWAPST                    1343
#define IDC_E_END                       1344
#define IDC_E_TEXTID                    1345
#define IDC_E_SOUNDID                   1346
#define IDC_E_OPENSEL                   1347
#define IDC_E_OPENSEL2                  1348
#define IDC_E_TRIGID                    1349
#define IDC_E_UCNSTID                   1350
#define IDC_E_CLEAR                     1351
#define IDC_E_TYPEVAL                   1352
#define IDC_E_VTYPE                     1353
#define IDC_E_NSELECTED                 1354
#define IDC_E_SIGGOAL                   1355
#define IDC_E_MAXHEALTH                 1356
#define IDC_C_TYPE                      1357
#define IDC_C_AMOUNT                    1358
#define IDC_C_RESTYPE                   1359
#define IDC_C_UIDOBJ                    1360
#define IDC_C_UIDLOC                    1361
#define IDC_C_UCNST                     1362
#define IDC_C_PLAYER                    1363
#define IDC_C_RESEARCH                  1364
#define IDC_C_TIMER                     1365
#define IDC_C_RESERVED                  1366
#define IDC_C_AREA_ALL                  1367
#define IDC_C_AREAX1                    1368
#define IDC_C_AREAY1                    1369
#define IDC_C_AREAX2                    1370
#define IDC_C_AREAY2                    1371
#define IDC_C_GROUP                     1372
#define IDC_C_UTYPE                     1373
#define IDC_C_AISIG                     1374
#define IDC_C_REVERSEHD                 1375
#define IDC_C_UNKNOWNHD                 1376
#define IDC_C_USEL1                     1377
#define IDC_C_USEL2                     1378
#define IDC_C_CLEAR                     1379
#define IDC_C_REVERSE                   1380
#define IDC_C_TYPEVAL                   1381
#define IDC_C_VTYPE                     1382
#define IDC_C_TAUNT_PLAYER              1383
#define IDC_C_TAUNT_SET                 1384
#define IDC_C_AIGOAL                    1385
#define ID_TS_FILE_NEW                  1386
#define ID_TS_FILE_OPEN                 1387
#define ID_TS_FILE_CLOSE                1388
#define ID_TS_FILE_SAVE                 1389
#define ID_TS_FILE_SAVE_AS              1390
#define ID_TS_FILE_SAVE_AS2             1391
#define ID_FILE_DUMP                    1392
#define ID_FILE_TRIGWRITE               1393
#define ID_FILE_TRIGREAD                1394
#define ID_FILE_REOPEN                  1395
#define ID_FILE_RECENT1                 1396
#define ID_FILE_RECENT2                 1397
#define ID_FILE_RECENT3                 1398
#define ID_FILE_RECENT4                 1399
#define ID_EDIT_RENAME                  1400
#define ID_TS_EDIT_COPY                 1401
#define ID_TS_EDIT_CUT                  1402
#define ID_TS_EDIT_PASTE                1403
#define ID_EDIT_DELETE                  1404
#define ID_EDIT_ALL                     1406
#define ID_VIEW_STAT_BAR                1407
#define ID_VIEW_STATISTICS              1408
#define ID_VIEW_MAP                     1409
#define ID_TS_APP_ABOUT                 1410
#define ID_TS_APP_EXIT                  1411
#define ID_TS_HELP                      1412
#define ID_TOOLS_COMPRESS               1413
#define ID_TOOLS_DECOMPRESS             1414
#define ID_TRIGGERS_SORT_CONDS_EFFECTS  1415
#define ID_TRIGGERS_HIDENAMES           1416
#define ID_TRIGGERS_HIDE_DESCRIPTIONS   1417
#define ID_TRIGGERS_SWAP_NAMES_DESCRIPTIONS 1418
#define ID_TRIGGERS_EXPAND_ALL          1419
#define ID_TRIGGERS_COMPATIBILITY       1420
#define ID_TRIGGERS_SAVE_PSEUDONYMS     1421
#define ID_UNITS_DELETE_ALL             1422
#define ID_MAP_WATER_CLIFF_INVISIBLE    1423
#define ID_MAP_WATER_CLIFF_VISIBLE      1424
#define ID_TRIGGERS_FIXTRIGGEROUTLIERS  1425
#define ID_TRIGGERS_NOPANEL             1426
#define ID_TRIGGERS_ZERODI              1427
#define ID_TRIGGERS_RESETDI             1428
#define ID_TRIGGERS_ZEROPANEL           1429
#define ID_TRIGGERS_HINTSPANEL          1430
#define ID_TRIGGERS_ZEROINSTRUCTIONSSOUNDID 1431
#define ID_TRIGGERS_NOINSTRUCTIONSSOUNDID 1432
#define ID_TRIGGERS_NOINSTRUCTIONSSOUND 1433
#define ID_DRAW_TERRAIN                 1434
#define ID_DRAW_ELEVATION               1435
#define ID_UNITS_TERRAIN_ELEV           1436

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
