//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by common.rc
//
#define VER_BUGFIX                      0x0000
#define VER_BUILD                       0x0000
#define VER_MAJOR                       0x0001
#define VER_MINOR                       0x00001
#define IDI_LOGO                        16
#define IDM_MAIN                        16
#define IDA_MAIN                        32
#define IDS_MAIN                        48
#define IDD_ABOUT                       101
#define IDD_STATS                       103
#define IDD_UNITSEL1                    104
#define IDD_UNITSEL2                    105
#define IDD_MSGS                        111
#define IDD_PLAYERSAI                   112
#define IDD_PLAYERSCTY                  113
#define IDD_VICTORY                     114
#define IDD_DISABLES                    115
#define IDD_TERRAIN                     116
#define IDD_UNITS                       117
#define IDD_TRIGGERS                    118
#define IDD_TRIGTEXT                    119
#define IDD_MAPINSPECT                  120
#define IDD_EFFECT                      121
#define IDD_COND                        122
#define IDB_LOGO                        200
#define IDB_TRIG_ON_GOOD                201
#define IDB_TRIG_ON_BAD                 202
#define IDB_TRIG_OFF_GOOD               203
#define IDB_TRIG_OFF_BAD                204
#define IDB_LOOP_ON_GOOD                205
#define IDB_LOOP_ON_BAD                 206
#define IDB_LOOP_OFF_GOOD               207
#define IDB_LOOP_OFF_BAD                208
#define IDB_COND_GOOD                   209
#define IDB_COND_BAD                    210
#define IDB_EFFECT_GOOD                 211
#define IDB_EFFECT_BAD                  212
#define IDC_M_MSGS                      1001
#define IDC_M_CINEM                     1002
#define IDC_M_STABLE                    1003
#define IDC_M_EXPORT                    1009
#define IDC_M_SEL                       1014
#define IDC_M_SELC                      1016
#define IDC_G_VER                       1050
#define IDC_S_PLAYERS                   1050
#define IDC_G_GAME                      1051
#define IDC_G_TIMESTAMP                 1052
#define IDC_S_TRIGGERS                  1052
#define IDC_G_ONAME                     1053
#define IDC_S_CONDITIONS                1053
#define IDC_S_EFFECTS                   1054
#define IDC_S_MAPSIZE                   1055
#define IDC_G_ALLTECHS                  1059
#define IDC_G_X                         1060
#define IDC_S_UNITS                     1060
#define IDC_G_Y                         1061
#define IDC_S_UNITS1                    1061
#define IDC_G_NEXTID                    1062
#define IDC_S_UNITS2                    1062
#define IDC_G_LOCKTEAMS                 1063
#define IDC_S_UNITS3                    1063
#define IDC_M_USERPATCH                 1064
#define IDC_S_UNITS4                    1064
#define IDC_G_CHOOSETEAMS               1065
#define IDC_S_UNITS5                    1065
#define IDC_G_RANDPOSITIONS             1066
#define IDC_S_UNITS6                    1066
#define IDC_S_UNITS7                    1067
#define IDC_S_UNITS8                    1068
#define IDC_S_UNITS9                    1069
#define IDC_S_DISABLE                   1070
#define IDC_S_DISABLE1                  1071
#define IDC_S_DISABLE2                  1072
#define IDC_S_DISABLE3                  1073
#define IDC_S_DISABLE4                  1074
#define IDC_S_DISABLE5                  1075
#define IDC_S_DISABLE6                  1076
#define IDC_S_DISABLE7                  1077
#define IDC_S_DISABLE8                  1078
#define IDC_S_DISABLE9                  1079
#define IDC_P_SP1                       1100
#define IDC_P_SP2                       1101
#define IDC_P_SP3                       1102
#define IDC_P_SP4                       1103
#define IDC_P_SP5                       1104
#define IDC_P_SP6                       1105
#define IDC_P_SP7                       1106
#define IDC_P_SP8                       1107
#define IDC_P_SG                        1108
#define IDC_P_CTY_SP1                   1109
#define IDC_P_CTY_SP2                   1110
#define IDC_P_CTY_SP3                   1111
#define IDC_P_CTY_SP4                   1112
#define IDC_P_CTY_SP5                   1113
#define IDC_P_CTY_SP6                   1114
#define IDC_P_CTY_SP7                   1115
#define IDC_P_CTY_SP8                   1116
#define IDC_P_CTY_SG                    1117
#define IDC_P_VC_SP1                    1118
#define IDC_P_VC_SP2                    1119
#define IDC_P_VC_SP3                    1120
#define IDC_P_VC_SP4                    1121
#define IDC_P_VC_SP5                    1122
#define IDC_P_VC_SP6                    1123
#define IDC_P_VC_SP7                    1124
#define IDC_P_VC_SP8                    1125
#define IDC_P_VC_SG                     1126
#define IDC_P_NAME                      1127
#define IDC_P_STABLE                    1128
#define IDC_P_ACTIVE                    1129
#define IDC_P_HUMAN                     1130
#define IDC_P_AI                        1131
#define IDC_P_CIV                       1132
#define IDC_P_POP                       1133
#define IDC_P_X                         1134
#define IDC_P_Y                         1135
#define IDC_P_COLOR                     1136
#define IDC_P_EXAI                      1137
#define IDC_P_FOOD                      1138
#define IDC_P_WOOD                      1139
#define IDC_P_GOLD                      1140
#define IDC_P_STONE                     1141
#define IDC_P_OREX                      1142
#define IDC_P_SPDIP                     1143
#define IDC_P_DSTATE                    1144
#define IDC_P_AV                        1145
#define IDC_P_IMAI                      1146
#define IDC_P_AGE                       1147
#define IDC_P_AIMODE                    1148
#define IDC_P_UF                        1149
#define IDC_P_US0                       1150
#define IDC_P_US1                       1151
#define IDC_P_LBL_FOOD                  1152
#define IDC_P_LBL_WOOD                  1153
#define IDC_P_LBL_GOLD                  1154
#define IDC_P_LBL_STONE                 1155
#define IDC_P_LBL_OREX                  1156
#define IDC_P_AISCRIPT                  1157
#define IDC_P_CLEARAI                   1158
#define IDC_P_RANDOMGAME                1159
#define IDC_P_PROMISORY                 1160
#define IDC_P_AIMODE_VAL                1161
#define IDC_P_SWAPP1                    1162
#define IDC_P_SWAPP2                    1163
#define IDC_P_SWAPP3                    1164
#define IDC_P_SWAPP4                    1165
#define IDC_P_SWAPP5                    1166
#define IDC_P_SWAPP6                    1167
#define IDC_P_SWAPP7                    1168
#define IDC_P_SWAPP8                    1169
#define IDC_P_SWAPGA                    1170
#define IDC_P_CLEARVC                   1171
#define IDC_P_IMVC                      1172
#define IDC_P_EXVC                      1173
#define IDC_P_CLEARCTY                  1174
#define IDC_P_IMCTY                     1175
#define IDC_P_EXCTY                     1176
#define IDC_P_VCSCRIPT                  1177
#define IDC_P_CTYSCRIPT                 1178
#define IDC_P_CTY                       1179
#define IDC_P_VC                        1180
#define IDC_P_OREY                      1181
#define IDC_P_LBL_OREY                  1182
#define IDC_P_NUM_PLAYERS               1183
#define IDC_P_MAX_TEAMS                 1184
#define IDC_T_TREE                      1185
#define IDC_P_TOAOFE                    1186
#define IDC_TT_VIEW                     1187
#define IDC_T_NAME                      1188
#define IDC_P_TO1C                      1189
#define IDC_TT_EXPORT                   1190
#define IDC_T_STATE                     1191
#define IDC_P_TOUP                      1192
#define IDC_TT_SEARCHTEXT               1193
#define IDC_T_LOOP                      1194
#define IDC_P_TOHD                      1195
#define IDC_TT_FINDNEXT                 1196
#define IDC_T_OBJ                       1197
#define IDC_TT_CONTEXT                  1198
#define IDC_T_ORDER                     1199
#define IDC_T_DESC                      1200
#define IDC_T_EDIT                      1201
#define IDC_T_NCOND                     1202
#define IDC_T_NEFFECT                   1203
#define IDC_T_DEL                       1204
#define IDC_T_ADD                       1205
#define IDC_T_DUPP                      1206
#define IDC_T_DESCID                    1207
#define IDC_T_OBJSTATE                  1208
#define IDC_T_UNKNOWN                   1209
#define IDC_T_GOTO                      1210
#define IDC_T_SHOWFIREORDER             1211
#define IDC_T_SHOWDISPLAYORDER          1212
#define IDC_T_SYNC                      1213
#define IDC_T_START                     1214
#define IDC_T_END                       1215
#define IDC_T_DEST                      1216
#define IDC_T_MOVE                      1217
#define IDC_T_DELETE                    1218
#define IDC_T_DUPRANGE                  1219
#define IDC_T_DESELECT                  1220
#define IDC_T_ADD_ACTIVATION            1221
#define IDC_T_PSEUDONYMS                1222
#define IDC_T_GOLIST                    1223
#define IDC_T_SOURCE                    1224
#define IDC_T_TARGET                    1225
#define IDC_V_SSTD                      1226
#define IDC_V_SCONQ                     1227
#define IDC_V_SSCORE                    1228
#define IDC_V_STIME                     1229
#define IDC_V_SCUSTOM                   1230
#define IDC_V_ALL                       1231
#define IDC_V_SCORE                     1232
#define IDC_V_TIME                      1233
#define IDC_V_RELICS                    1234
#define IDC_V_EXPL                      1235
#define IDC_V_CONQUEST                  1236
#define IDC_TR_AITYPE                   1237
#define IDC_TR_SIZE                     1238
#define IDC_TR_TX                       1239
#define IDC_TR_TY                       1240
#define IDC_TR_ID                       1241
#define IDC_TR_ELEV                     1242
#define IDC_TR_MCPASTE                  1243
#define IDC_TR_MCCOPY                   1244
#define IDC_TR_SIZE2                    1245
#define IDC_TR_MMX1                     1246
#define IDC_TR_MMY1                     1247
#define IDC_TR_MMSET1                   1248
#define IDC_TR_MMX2                     1249
#define IDC_TR_MMY2                     1250
#define IDC_TR_MMSET2                   1251
#define IDC_TR_MMXT                     1252
#define IDC_TR_MMYT                     1253
#define IDC_TR_MMSETT                   1254
#define IDC_TR_MMMOVE                   1255
#define IDC_TR_MDUPT                    1256
#define IDC_TR_MDUPU                    1257
#define IDC_TR_NORMALIZE_ELEV           1258
#define IDC_TR_SAVETILE                 1259
#define IDC_TR_MDUPE                    1260
#define IDC_TR_FACTOR                   1261
#define IDC_TR_SCALE                    1262
#define IDC_TABS                        1263
#define IDC_TR_MOVE_TERRAIN             1264
#define IDC_TR_MOVE_UNITS               1265
#define IDC_TR_MOVE_ELEVATION           1266
#define IDC_TR_MOVE_TRIGGERS            1267
#define IDC_TR_MMSWAP                   1268
#define IDC_TR_SWAP_TERRAIN             1269
#define IDC_TR_SWAP_UNITS               1270
#define IDC_TR_SWAP_ELEVATION           1271
#define IDC_TR_SWAP_TRIGGERS            1272
#define IDC_TR_MDUPTR                   1273
#define IDC_TR_RMUNITS                  1274
#define IDC_TR_RMTRIGS                  1275
#define IDC_TR_REPEAT                   1276
#define IDC_TR_REPEAT_UNITS             1277
#define IDC_TR_REPEAT_TERRAIN           1278
#define IDC_TR_REPEAT_ELEV              1279
#define IDC_TR_CONST                    1280
#define IDC_TR_FLOOD                    1281
#define IDC_TR_OUTLINE                  1282
#define IDC_TR_OUTLINE_FORCE            1283
#define IDC_TR_SWAP_TERRAIN_TYPES       1284
#define IDC_TR_OUTLINE_FORCE_EIGHT      1285
#define IDC_TR_OUTLINE_EIGHT            1286
#define IDC_TR_RAISE_ELEV               1287
#define IDC_TR_LOWER_ELEV               1288
#define IDC_TR_FLOOD_ELEV               1289
#define IDC_TR_UNK1                     1290
#define IDC_TR_UNK2                     1291
#define IDC_TR_UNK3                     1292
#define IDC_TR_UNK4                     1293
#define IDC_TR_CLEAR                    1294
#define IDC_U_SELU                      1295
#define IDC_U_SELP                      1296
#define IDC_U_TYPE                      1297
#define IDC_U_UNIT                      1298
#define IDC_U_CONST                     1299
#define IDC_U_X                         1300
#define IDC_U_Y                         1301
#define IDC_U_ROTATE                    1302
#define IDC_U_FRAME                     1303
#define IDC_U_ADD                       1304
#define IDC_U_DEL                       1305
#define IDC_U_GARRISON                  1306
#define IDC_U_SORT                      1307
#define IDC_U_ID                        1308
#define IDC_U_STATE                     1309
#define IDC_U_Z                         1310
#define IDC_U_NEXT_AVAIL                1311
#define IDC_STATIC_NEXT_AVAIL           1312
#define IDC_U_COMPRESS                  1313
#define IDC_U_RENUMBER                  1314
#define IDC_U_MAKEP1                    1315
#define IDC_U_MAKEP2                    1316
#define IDC_U_MAKEP3                    1317
#define IDC_U_MAKEP4                    1318
#define IDC_U_MAKEP5                    1319
#define IDC_U_MAKEP6                    1320
#define IDC_U_MAKEP7                    1321
#define IDC_U_MAKEP8                    1322
#define IDC_U_MAKEGA                    1323
#define IDC_U_RANDOMIZE_ROT             1324
#define IDC_U_DEL_TYPE                  1325
#define IDC_U_ROTATE_VAL                1326
#define IDC_U_DESELECT                  1327
#define IDC_U_RESORT                    1328
#define IDC_D_SPLY                      1329
#define IDC_D_STYPE                     1330
#define IDC_D_ALL                       1331
#define IDC_D_SEL                       1332
#define IDC_D_CLR                       1333
#define IDC_D_DEL                       1334
#define IDC_D_ADD                       1335
#define IDC_D_FILL                      1336
#define IDC_US_UNITS                    1337
#define IDC_US_SORT                     1338
#define IDC_US_PLAYER                   1339
#define IDC_US_NOTE                     1340
#define IDC_E_TYPE                      1341
#define IDC_E_AIGOAL                    1342
#define IDC_E_AMOUNT                    1343
#define IDC_E_RESTYPE                   1344
#define IDC_E_DSTATE                    1345
#define IDC_E_UIDS                      1346
#define IDC_E_LOCUID                    1347
#define IDC_E_UCNST                     1348
#define IDC_E_SPLAY                     1349
#define IDC_E_TPLAY                     1350
#define IDC_E_RESEARCH                  1351
#define IDC_E_TEXT                      1352
#define IDC_E_SOUND                     1353
#define IDC_E_DTIME                     1354
#define IDC_E_TRIG                      1355
#define IDC_E_LOCX                      1356
#define IDC_E_LOCY                      1357
#define IDC_E_AREAX1                    1358
#define IDC_E_AREAY1                    1359
#define IDC_E_AREAX2                    1360
#define IDC_E_AREAY2                    1361
#define IDC_E_AREA_ALL                  1362
#define IDC_E_GROUP                     1363
#define IDC_E_UTYPE                     1364
#define IDC_E_PANEL                     1365
#define IDC_E_STANCE                    1366
#define IDC_E_SWAPST                    1367
#define IDC_E_END                       1368
#define IDC_E_TEXTID                    1369
#define IDC_E_SOUNDID                   1370
#define IDC_E_OPENSEL                   1371
#define IDC_E_OPENSEL2                  1372
#define IDC_E_TRIGID                    1373
#define IDC_E_UCNSTID                   1374
#define IDC_E_CLEAR                     1375
#define IDC_E_TYPEVAL                   1376
#define IDC_E_VTYPE                     1377
#define IDC_E_NSELECTED                 1378
#define IDC_E_SIGGOAL                   1379
#define IDC_E_MAXHEALTH                 1380
#define IDC_C_TYPE                      1381
#define IDC_C_AMOUNT                    1382
#define IDC_C_RESTYPE                   1383
#define IDC_C_UIDOBJ                    1384
#define IDC_C_UIDLOC                    1385
#define IDC_C_UCNST                     1386
#define IDC_C_PLAYER                    1387
#define IDC_C_RESEARCH                  1388
#define IDC_C_TIMER                     1389
#define IDC_C_RESERVED                  1390
#define IDC_C_AREA_ALL                  1391
#define IDC_C_AREAX1                    1392
#define IDC_C_AREAY1                    1393
#define IDC_C_AREAX2                    1394
#define IDC_C_AREAY2                    1395
#define IDC_C_GROUP                     1396
#define IDC_C_UTYPE                     1397
#define IDC_C_AISIG                     1398
#define IDC_C_REVERSEHD                 1399
#define IDC_C_UNKNOWNHD                 1400
#define IDC_C_USEL1                     1401
#define IDC_C_USEL2                     1402
#define IDC_C_CLEAR                     1403
#define IDC_C_REVERSE                   1404
#define IDC_C_TYPEVAL                   1405
#define IDC_C_VTYPE                     1406
#define IDC_C_TAUNT_PLAYER              1407
#define IDC_C_TAUNT_SET                 1408
#define IDC_C_AIGOAL                    1409
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_SAVE_AS2                0xE105
#define ID_FILE_DUMP                    0xE106
#define ID_FILE_TRIGWRITE               0xE107
#define ID_FILE_TRIGREAD                0xE108
#define ID_FILE_REOPEN                  0xE109
#define ID_FILE_RECENT1                 0xE110
#define ID_FILE_RECENT2                 0xE111
#define ID_FILE_RECENT3                 0xE112
#define ID_FILE_RECENT4                 0xE113
#define ID_EDIT_RENAME                  0xE120
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_DELETE                  0xE126
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_ALL                     0xE12C
#define ID_VIEW_STAT_BAR                0xE131
#define ID_VIEW_STATISTICS              0xE132
#define ID_VIEW_MAP                     0xE133
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP                         0xE146
#define ID_TOOLS_COMPRESS               0xE150
#define ID_TOOLS_DECOMPRESS             0xE151
#define ID_TRIGGERS_SORT_CONDS_EFFECTS  0xE152
#define ID_TRIGGERS_HIDENAMES           0xE153
#define ID_TRIGGERS_HIDE_DESCRIPTIONS   0xE154
#define ID_TRIGGERS_SWAP_NAMES_DESCRIPTIONS 0xE155
#define ID_TRIGGERS_EXPAND_ALL          0xE156
#define ID_TRIGGERS_COMPATIBILITY       0xE157
#define ID_TRIGGERS_SAVE_PSEUDONYMS     0xE158
#define ID_UNITS_DELETE_ALL             0xE159
#define ID_MAP_WATER_CLIFF_INVISIBLE    0xE15A
#define ID_MAP_WATER_CLIFF_VISIBLE      0xE15B
#define ID_TRIGGERS_FIXTRIGGEROUTLIERS  0xE15C
#define ID_TRIGGERS_NOPANEL             0xE15D
#define ID_TRIGGERS_ZERODI              0xE15E
#define ID_TRIGGERS_RESETDI             0xE15F
#define ID_TRIGGERS_ZEROPANEL           0xE160
#define ID_TRIGGERS_HINTSPANEL          0xE161
#define ID_TRIGGERS_ZEROINSTRUCTIONSSOUNDID 0xE162
#define ID_TRIGGERS_NOINSTRUCTIONSSOUNDID 0xE163
#define ID_TRIGGERS_NOINSTRUCTIONSSOUND 0xE164
#define ID_DRAW_TERRAIN                 0xE165
#define ID_DRAW_ELEVATION               0xE166
#define ID_UNITS_TERRAIN_ELEV           0xE167

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
